#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include <globals.hpp>
#include <interface/metadata.hpp>
#include <interface/state_descriptor.hpp>
#include <kokkos_abstraction.hpp>
#include <parthenon_manager.hpp>

#include "energy_transfer/convert.hpp"
#include "energy_transfer/field_spec.hpp"
#include "energy_transfer/ingest.hpp"
#include "energy_transfer/shell_transfer.hpp"
#include "energy_transfer/spectra.hpp"

using parthenon::Real;

namespace {

enum { IDN = 0, IV1 = 1, IV2 = 2, IV3 = 3, IPR = 4, IB1 = 5, IB2 = 6, IB3 = 7, NPRIM = 8 };

parthenon::Packages_t ProcessPackages(std::unique_ptr<parthenon::ParameterInput> &) {
  parthenon::Packages_t packages;
  auto package = std::make_shared<parthenon::StateDescriptor>("test_refactor_baseline");
  auto m = parthenon::Metadata({parthenon::Metadata::Cell, parthenon::Metadata::Derived,
                                parthenon::Metadata::OneCopy, parthenon::Metadata::Vector},
                               std::vector<int>{NPRIM});
  package->AddField("prim", m);
  packages.Add(package);
  return packages;
}

// Serializes every matrix/spectrum entry deterministically -- std::setprecision(17)
// round-trips a double exactly, so a line-by-line text diff is a genuine bitwise check.
std::vector<std::string> SerializeResult(const energy_transfer::TransferResult &result) {
  std::vector<std::string> lines;
  std::ostringstream oss;
  oss << std::setprecision(17);
  for (auto &[name, mat] : result.matrices) {
    for (int qi = 0; qi < static_cast<int>(mat.extent(0)); qi++) {
      for (int mi = 0; mi < static_cast<int>(mat.extent(1)); mi++) {
        for (int ki = 0; ki < static_cast<int>(mat.extent(2)); ki++) {
          oss.str("");
          oss << "TERM " << name << ' ' << qi << ' ' << mi << ' ' << ki << ' ' << mat(qi, mi, ki);
          lines.push_back(oss.str());
        }
      }
    }
  }
  for (auto &[name, sarr] : result.spectra) {
    for (int bin = 0; bin < static_cast<int>(sarr.extent(0)); bin++) {
      for (int col = 0; col < static_cast<int>(sarr.extent(1)); col++) {
        oss.str("");
        oss << "SPEC " << name << ' ' << bin << ' ' << col << ' ' << sarr(bin, col);
        lines.push_back(oss.str());
      }
    }
  }
  return lines;
}

bool HasSuffix(const std::string &s, const std::string &suffix) {
  return s.size() >= suffix.size() &&
        s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
}

// The one documented, intentional behavior change from the spectra/decomposition
// refactor: bin 0 (the DC mode) of a decomposed spectrum's compressive/plus/minus
// component no longer follows the old "assign the whole mode to compressive"
// convention -- direction is genuinely undefined at k=0, so all three are exactly
// 0 there instead. See decomposition.hpp's file-level comment. Lines like this are
// excluded from the comparison rather than required to match.
bool IsExpectedDiffLine(const std::string &line) {
  std::istringstream iss(line);
  std::string tag, name;
  int bin = -1;
  if (!(iss >> tag >> name >> bin)) return false;
  if (tag != "SPEC" || bin != 0) return false;
  return HasSuffix(name, "_compressive") || HasSuffix(name, "_plus") || HasSuffix(name, "_minus");
}

} // namespace

// Bitwise-regression baseline for the spectra/energy-transfer separation refactor:
// the checked-in golden file (test/refactor_baseline_golden.txt) was generated by
// this same test BEFORE the refactor (via the since-removed, fused
// ComputeShellTransferLive) for a fixed set of terms (U-mediated UUA/BBA,
// b-mediated UBTb, with all three axes decomposed to exercise the mediator-
// decomposition sweep too) and spectra (every plain spectrum plus every
// decomposed bundle). This version of the test computes the same thing via the
// post-refactor split entry points (GatherLiveFields + ComputeEnergyTransfer +
// ComputeSpectra) and compares against that golden file, so the refactor can be
// verified to change nothing -- except the one documented, intentional bin-0
// exception above -- far faster than re-running the expensive, off-by-default
// gold_standard_dd0024 Python comparison.
//
// Usage: test_refactor_baseline -i synthetic.in --golden <path>
//   If <path> doesn't exist yet, writes it (first-run/generation mode) and exits 0.
//   If it exists, recomputes and compares line-by-line (ignoring lines
//   IsExpectedDiffLine() flags on either side) and reports PASS/FAIL.
int main(int argc, char *argv[]) {
  std::string golden_path;
  std::vector<char *> parthenon_argv;
  for (int i = 0; i < argc; i++) {
    if (std::string(argv[i]) == "--golden" && i + 1 < argc) {
      golden_path = argv[i + 1];
      i++;
    } else {
      parthenon_argv.push_back(argv[i]);
    }
  }
  if (golden_path.empty()) {
    std::cerr << "test_refactor_baseline: --golden <path> is required.\n";
    return 1;
  }
  int p_argc = static_cast<int>(parthenon_argv.size());
  parthenon_argv.push_back(nullptr); // OpenMPI's MPI_Init expects a NULL-terminated argv

  parthenon::ParthenonManager pman;
  pman.app_input->ProcessPackages = ProcessPackages;
  pman.app_input->ProblemGenerator = [](parthenon::MeshBlock *pmb, parthenon::ParameterInput *) {
    auto &rc = pmb->meshblock_data.Get();
    auto prim = rc->PackVariables(std::vector<std::string>{"prim"});
    auto ib = pmb->cellbounds.GetBoundsI(parthenon::IndexDomain::interior);
    auto jb = pmb->cellbounds.GetBoundsJ(parthenon::IndexDomain::interior);
    auto kb = pmb->cellbounds.GetBoundsK(parthenon::IndexDomain::interior);
    const int Nx = pmb->pmy_mesh->mesh_size.nx(parthenon::X1DIR);
    parthenon::par_for(
        "FillPrim", kb.s, kb.e, jb.s, jb.e, ib.s, ib.e,
        KOKKOS_LAMBDA(const int k, const int j, const int i) {
          prim(IDN, k, j, i) = 1.0;
          prim(IPR, k, j, i) = 1.0;
          prim(IV1, k, j, i) = Kokkos::cos(2.0 * M_PI * 3 * i / Real(Nx)) +
                              0.5 * Kokkos::sin(2.0 * M_PI * 5 * i / Real(Nx));
          prim(IV2, k, j, i) = 0.3 * Kokkos::cos(2.0 * M_PI * 2 * j / Real(Nx));
          // Pure-kz mode -- exercises BuildHelicalBasis's kperp==0 fallback.
          prim(IV3, k, j, i) = 0.4 * Kokkos::sin(2.0 * M_PI * 4 * k / Real(Nx));
          prim(IB1, k, j, i) = 0.2 * Kokkos::cos(2.0 * M_PI * 2 * i / Real(Nx)) +
                              0.1 * Kokkos::sin(2.0 * M_PI * 1 * i / Real(Nx));
          prim(IB2, k, j, i) = 0.15 * Kokkos::sin(2.0 * M_PI * 3 * j / Real(Nx));
          prim(IB3, k, j, i) = 0.1 * Kokkos::cos(2.0 * M_PI * 1 * k / Real(Nx));
        });
  };

  auto status = pman.ParthenonInitEnv(p_argc, parthenon_argv.data());
  if (status != parthenon::ParthenonStatus::ok) {
    pman.ParthenonFinalize();
    return status == parthenon::ParthenonStatus::complete ? 0 : 1;
  }
  pman.ParthenonInitPackagesAndMesh();

  int result_code = 0;
  {
    auto *pmesh = pman.pmesh.get();
    auto &md = pmesh->mesh_data.Get();
    auto spec = energy_transfer::MakeAthenaPKPrimitiveLiveSpec(IDN, IV1, IV2, IV3, IPR,
                                                                /*has_bfield=*/true, IB1, IB2, IB3);

    energy_transfer::ShellTransferConfig cfg;
    cfg.donor_binning = cfg.mediator_binning = cfg.receiver_binning =
        energy_transfer::BinningSpec::Linear(4);
    cfg.terms = {"UUA", "BBA", "UBTb"};
    cfg.mode = energy_transfer::DecompositionMode{true, true, true};
    const std::vector<std::string> spectrum_names = {
        "spec_U",        "spec_rho",      "spec_W",       "spec_B",
        "spec_U_decomp", "spec_W_decomp", "spec_B_decomp"};

    auto fields = energy_transfer::GatherLiveFields(pmesh, md.get(), spec);
    energy_transfer::ConvertConservedToPrimitive(fields);

    auto res = energy_transfer::ComputeEnergyTransfer(pmesh, fields, cfg);
    res.spectra = energy_transfer::ComputeSpectra(pmesh, fields, spectrum_names);
    auto lines = SerializeResult(res);
    std::sort(lines.begin(), lines.end());

    std::ifstream existing(golden_path);
    if (!existing.good()) {
      std::ofstream out(golden_path);
      for (auto &line : lines) out << line << '\n';
      if (parthenon::Globals::my_rank == 0) {
        std::cout << "GENERATED: wrote " << lines.size() << " lines to " << golden_path
                  << std::endl;
      }
    } else {
      std::vector<std::string> golden_lines;
      std::string line;
      while (std::getline(existing, line)) golden_lines.push_back(line);

      std::vector<std::string> golden_filtered, live_filtered;
      for (auto &l : golden_lines) {
        if (!IsExpectedDiffLine(l)) golden_filtered.push_back(l);
      }
      for (auto &l : lines) {
        if (!IsExpectedDiffLine(l)) live_filtered.push_back(l);
      }
      const bool ok = (golden_filtered == live_filtered);

      if (parthenon::Globals::my_rank == 0) {
        if (ok) {
          std::cout << "PASS: live output matches " << golden_path << " (" << live_filtered.size()
                    << " compared lines, bin-0 compressive/plus/minus lines exempted).\n";
        } else {
          std::cout << "FAIL: live output does not match " << golden_path << ".\n";
        }
      }
      result_code = ok ? 0 : 1;
    }
  }

  pman.ParthenonFinalize();
  return result_code;
}
